/**
 * Picory 상품 페이지 — 더미 상품 데이터 (thumbnail, categories 필수)
 * 썸네일 경로: 사이트 루트 기준 images/cameras (정적 배포 시 public 동일)
 */
export const PICORY_PRODUCT_MOCK = [
  {
    id: 'fujifilm-x100vi',
    brand: 'Fujifilm',
    model: 'X100VI',
    /** 정렬용: 대략 최저가(원), 인기순 가중치 */
    priceKrw: 2190000,
    popularity: 98,
    description: '고정 렌즈와 필름 시뮬레이션으로 스냅·일상 기록에 강한 풀프레임급 인기 모델입니다.',
    priceSummary: '약 2,190,000원대 · 정가 기준',
    platform: '네이버 쇼핑 · 쿠팡 · 공식몰',
    thumbnail: '/images/cameras/fujifilm-x100vi.png',
    categories: ['trending', 'emotional', 'community-picks'],
  },
  {
    id: 'canon-eos-r10',
    brand: 'Canon',
    model: 'EOS R10',
    priceKrw: 920000,
    popularity: 82,
    description: '가벼운 APS-C 미러리스로 조작이 단순해 입문용 바디로 많이 선택됩니다.',
    priceSummary: '약 920,000원대 ~',
    platform: '쿠팡 · 다나와 · 중고나라',
    thumbnail: '/images/cameras/canon-eos-r10.png',
    categories: ['beginner', 'value', 'travel'],
  },
  {
    id: 'sony-zv-e10-ii',
    brand: 'Sony',
    model: 'ZV-E10 II',
    priceKrw: 1280000,
    popularity: 92,
    description: '브이로그에 맞춘 자동 모드와 마이크 단자 구성이 강점인 APS-C 기종입니다.',
    priceSummary: '약 1,280,000원대 ~',
    platform: '네이버 · 공식 스토어 · 온라인 면세',
    thumbnail: '/images/cameras/sony-zv-e10-ii.png',
    categories: ['vlog', 'beginner', 'trending'],
  },
  {
    id: 'ricoh-gr-iiix',
    brand: 'Ricoh',
    model: 'GR IIIx',
    priceKrw: 1590000,
    popularity: 88,
    description: '40mm 화각의 스냅 특화 컴팩트로 주머니에 넣고 다니기 좋습니다.',
    priceSummary: '약 1,590,000원대 ~',
    platform: '공식몰 · 온라인 · 중고',
    thumbnail: '/images/cameras/ricoh-gr-iiix.png',
    categories: ['travel', 'emotional', 'trending'],
  },
  {
    id: 'sony-a7c-ii',
    brand: 'Sony',
    model: 'A7C II',
    priceKrw: 2390000,
    popularity: 96,
    description: '풀프레임 센서를 작은 바디에 담아 인물·여행·브이로그까지 균형이 좋습니다.',
    priceSummary: '약 2,390,000원대 ~',
    platform: '다나와 · 쿠팡 · 오프라인 대리점',
    thumbnail: '/images/cameras/sony-a7c-ii.png',
    categories: ['trending', 'emotional', 'vlog'],
  },
  {
    id: 'nikon-z-fc',
    brand: 'Nikon',
    model: 'Z fc',
    priceKrw: 1190000,
    popularity: 80,
    description: '필름 SLR 감성의 다이얼 조작과 vari-angle LCD가 매력인 APS-C 바디입니다.',
    priceSummary: '약 1,190,000원대 ~',
    platform: '네이버 · 공식몰 · 중고나라',
    thumbnail: '/images/cameras/nikon-z-fc.png',
    categories: ['vintage', 'emotional', 'travel'],
  },
  {
    id: 'canon-g7x-mark-iii',
    brand: 'Canon',
    model: 'PowerShot G7 X Mark III',
    priceKrw: 950000,
    popularity: 90,
    description: '1인치 센서 컴팩트로 4K 영상과 수직 촬영에 적합한 휴대형 기종입니다.',
    priceSummary: '약 950,000원대 ~',
    platform: '쿠팡 · 온라인 면세 · 중고',
    thumbnail: '/images/cameras/canon-g7x-mark-iii.png',
    categories: ['vlog', 'travel', 'value'],
  },
  {
    id: 'dji-osmo-pocket-3',
    brand: 'DJI',
    model: 'Osmo Pocket 3',
    priceKrw: 649000,
    popularity: 91,
    description: '3축 짐벌 일체형 포켓 캠으로 손떨림 보정이 강한 영상 기기입니다.',
    priceSummary: '약 649,000원대 ~',
    platform: '공식 스토어 · 쿠팡 · 면세',
    thumbnail: '/images/cameras/dji-osmo-pocket-3.png',
    categories: ['vlog', 'travel', 'trending'],
  },
  {
    id: 'sony-a6700',
    brand: 'Sony',
    model: 'A6700',
    priceKrw: 1520000,
    popularity: 94,
    description: '최신 APS-C AF 성능과 4K 120p(크롭) 등 영상 옵션이 풍부한 올라운더입니다.',
    priceSummary: '약 1,520,000원대 ~',
    platform: '다나와 · 네이버 · 중고',
    thumbnail: '/images/cameras/sony-a6700.png',
    categories: ['trending', 'vlog', 'travel', 'beginner'],
  },
  {
    id: 'canon-eos-r50',
    brand: 'Canon',
    model: 'EOS R50',
    priceKrw: 980000,
    popularity: 93,
    description: '가볍고 가격 부담이 적어 첫 미러리스로 무난한 입문 모델입니다.',
    priceSummary: '약 980,000원대 ~',
    platform: '쿠팡 · 온라인 · 중고나라',
    thumbnail: '/images/cameras/canon-eos-r50.png',
    categories: ['beginner', 'value', 'trending'],
  },
  {
    id: 'fujifilm-x-s20',
    brand: 'Fujifilm',
    model: 'X-S20',
    priceKrw: 1780000,
    popularity: 87,
    description: '손떨림 보정과 배터리 용량이 좋아 사진·영상 겸용으로 인기입니다.',
    priceSummary: '약 1,780,000원대 ~',
    platform: '공식몰 · 다나와 · 중고',
    thumbnail: '/images/cameras/fujifilm-x-s20.png',
    categories: ['emotional', 'vlog', 'beginner'],
  },
  {
    id: 'canon-eos-r50-v',
    brand: 'Canon',
    model: 'EOS R50 V',
    priceKrw: 1180000,
    popularity: 79,
    description: '세로 영상·라이브에 맞춘 UI와 입문형 조작이 강점인 V 시리즈입니다.',
    priceSummary: '약 1,180,000원대 ~',
    platform: '네이버 · 쿠팡 · 공식',
    thumbnail: '/images/cameras/canon-eos-r50-v.png',
    categories: ['vlog', 'beginner', 'trending'],
  },
];
