/**
 * Picory 상품 페이지 — 더미 상품 데이터 (thumbnail, categories 필수)
 * 썸네일 경로: 사이트 루트 기준 images/cameras (정적 배포 시 public 동일)
 */
export const PICORY_PRODUCT_MOCK = [
  {
    id: 'fujifilm-x100vi',
    brand: 'Fujifilm',
    model: 'X100VI',
    /** 정렬용: 대략 최저가(원), 인기순 가중치 */
    priceKrw: 2190000,
    popularity: 98,
    description: '고정 렌즈와 필름 시뮬레이션으로 스냅·일상 기록에 강한 풀프레임급 인기 모델입니다.',
    priceSummary: '약 2,190,000원대 · 정가 기준',
    platform: '네이버 쇼핑 · 쿠팡 · 공식몰',
    thumbnail: '/images/cameras/fujifilm-x100vi.png',
    categories: ['trending', 'emotional', 'travel'],
  },
  {
    id: 'canon-eos-r10',
    brand: 'Canon',
    model: 'EOS R10',
    priceKrw: 920000,
    popularity: 82,
    description: '가벼운 APS-C 미러리스로 조작이 단순해 입문용 바디로 많이 선택됩니다.',
    priceSummary: '약 920,000원대 ~',
    platform: '쿠팡 · 다나와 · 중고나라',
    thumbnail: 'https://www.kenrockwell.com/canon/eos-r/images/r10/D3S_0108-1200.jpg',
    categories: ['beginner', 'value', 'travel'],
  },
  {
    id: 'sony-zv-e10-ii',
    brand: 'Sony',
    model: 'ZV-E10 II',
    priceKrw: 1280000,
    popularity: 92,
    description: '브이로그에 맞춘 자동 모드와 마이크 단자 구성이 강점인 APS-C 기종입니다.',
    priceSummary: '약 1,280,000원대 ~',
    platform: '네이버 · 공식 스토어 · 온라인 면세',
    thumbnail: '/images/cameras/sony-zv-e10-ii.png',
    categories: ['vlog', 'beginner', 'trending'],
  },
  {
    id: 'ricoh-gr-iiix',
    brand: 'Ricoh',
    model: 'GR IIIx',
    priceKrw: 1590000,
    popularity: 88,
    description: '40mm 화각의 스냅 특화 컴팩트로 주머니에 넣고 다니기 좋습니다.',
    priceSummary: '약 1,590,000원대 ~',
    platform: '공식몰 · 온라인 · 중고',
    thumbnail: '/images/cameras/ricoh-gr-iiix.png',
    categories: ['travel', 'emotional', 'trending'],
  },
  {
    id: 'sony-a7c-ii',
    brand: 'Sony',
    model: 'A7C II',
    priceKrw: 2390000,
    popularity: 96,
    description: '풀프레임 센서를 작은 바디에 담아 인물·여행·브이로그까지 균형이 좋습니다.',
    priceSummary: '약 2,390,000원대 ~',
    platform: '다나와 · 쿠팡 · 오프라인 대리점',
    thumbnail: '/images/cameras/sony-a7c-ii.png',
    categories: ['trending', 'emotional', 'vlog'],
  },
  {
    id: 'nikon-z-fc',
    brand: 'Nikon',
    model: 'Z fc',
    priceKrw: 1190000,
    popularity: 80,
    description: '필름 SLR 감성의 다이얼 조작과 vari-angle LCD가 매력인 APS-C 바디입니다.',
    priceSummary: '약 1,190,000원대 ~',
    platform: '네이버 · 공식몰 · 중고나라',
    thumbnail: 'https://2.img-dpreview.com/files/p/TS60x60PFFFFFF00~products/nikon_zfc/c12f842d4d1a40beb20e7264c1ceccda.png',
    categories: ['vintage', 'emotional', 'travel'],
  },
  {
    id: 'canon-g7x-mark-iii',
    brand: 'Canon',
    model: 'PowerShot G7 X Mark III',
    priceKrw: 950000,
    popularity: 90,
    description: '1인치 센서 컴팩트로 4K 영상과 수직 촬영에 적합한 휴대형 기종입니다.',
    priceSummary: '약 950,000원대 ~',
    platform: '쿠팡 · 온라인 면세 · 중고',
    thumbnail: 'https://img.photographyblog.com/reviews/canon_power_shot_g7_x_mark_iii/sample_images/canon_power_shot_g7_x_mark_iii_01.jpg',
    categories: ['vlog', 'travel', 'value'],
  },
  {
    id: 'dji-osmo-pocket-3',
    brand: 'DJI',
    model: 'Osmo Pocket 3',
    priceKrw: 649000,
    popularity: 91,
    description: '3축 짐벌 일체형 포켓 캠으로 손떨림 보정이 강한 영상 기기입니다.',
    priceSummary: '약 649,000원대 ~',
    platform: '공식 스토어 · 쿠팡 · 면세',
    thumbnail: '/images/cameras/dji-osmo-pocket-3.png',
    categories: ['vlog', 'travel', 'trending'],
  },
  {
    id: 'sony-a6700',
    brand: 'Sony',
    model: 'A6700',
    priceKrw: 1520000,
    popularity: 94,
    description: '최신 APS-C AF 성능과 4K 120p(크롭) 등 영상 옵션이 풍부한 올라운더입니다.',
    priceSummary: '약 1,520,000원대 ~',
    platform: '다나와 · 네이버 · 중고',
    thumbnail: '/images/cameras/sony-a6700.png',
    categories: ['trending', 'vlog', 'travel', 'beginner'],
  },
  {
    id: 'canon-eos-r50',
    brand: 'Canon',
    model: 'EOS R50',
    priceKrw: 980000,
    popularity: 93,
    description: '가볍고 가격 부담이 적어 첫 미러리스로 무난한 입문 모델입니다.',
    priceSummary: '약 980,000원대 ~',
    platform: '쿠팡 · 온라인 · 중고나라',
    thumbnail: '/images/cameras/canon-eos-r50.png',
    categories: ['beginner', 'value', 'trending'],
  },
  {
    id: 'fujifilm-x-s20',
    brand: 'Fujifilm',
    model: 'X-S20',
    priceKrw: 1780000,
    popularity: 87,
    description: '손떨림 보정과 배터리 용량이 좋아 사진·영상 겸용으로 인기입니다.',
    priceSummary: '약 1,780,000원대 ~',
    platform: '공식몰 · 다나와 · 중고',
    thumbnail: 'https://img.photographyblog.com/reviews/fujifilm_x_s20/sample_images/fujifilm_x_s20_01.jpg',
    categories: ['emotional', 'vlog', 'beginner'],
  },
  {
    id: 'canon-eos-r50-v',
    brand: 'Canon',
    model: 'EOS R50 V',
    priceKrw: 1180000,
    popularity: 79,
    description: '세로 영상·라이브에 맞춘 UI와 입문형 조작이 강점인 V 시리즈입니다.',
    priceSummary: '약 1,180,000원대 ~',
    platform: '네이버 · 쿠팡 · 공식',
    thumbnail: '/images/cameras/canon-eos-r50-v.png',
    categories: ['vlog', 'beginner', 'trending'],
  },
  {
    id: 'nikon-z50ii',
    brand: 'Nikon',
    model: 'Z50II',
    priceKrw: 1290000,
    popularity: 89,
    description: 'EXPEED 7과 피사체 인식 AF를 갖춘 APS-C 미러리스로 가족·여행·영상까지 균형이 좋습니다.',
    priceSummary: '약 1,290,000원대 ~',
    platform: '네이버 · 중고나라 · 공식몰',
    thumbnail: '/images/cameras/nikon-z50ii.png',
    categories: ['beginner', 'travel', 'trending'],
  },
  {
    id: 'canon-eos-r8',
    brand: 'Canon',
    model: 'EOS R8',
    priceKrw: 1890000,
    popularity: 86,
    description: '가벼운 풀프레임 바디에 빠른 AF와 4K 60p를 담아 인물·여행용으로 접근성이 좋습니다.',
    priceSummary: '약 1,890,000원대 ~',
    platform: '쿠팡 · 네이버 · 다나와',
    thumbnail: 'https://img.photographyblog.com/reviews/canon_eos_r8/sample_images/canon_eos_r8_01.jpg',
    categories: ['travel', 'emotional', 'value'],
  },
  {
    id: 'sony-rx100-vii',
    brand: 'Sony',
    model: 'RX100 VII',
    priceKrw: 1490000,
    popularity: 84,
    description: '작은 바디에 빠른 AF와 고배율 줌을 담은 프리미엄 컴팩트로 여행 기록에 강합니다.',
    priceSummary: '약 1,490,000원대 ~',
    platform: '네이버 · 쿠팡 · 중고',
    thumbnail: 'https://img.photographyblog.com/reviews/sony_cyber_shot_rx100_vii/sample_images/sony_cyber_shot_rx100_vii_01.jpg',
    categories: ['travel', 'value', 'vlog'],
  },
  {
    id: 'panasonic-lumix-s9',
    brand: 'Panasonic',
    model: 'Lumix S9',
    priceKrw: 1990000,
    popularity: 83,
    description: 'LUT 기반 컬러 워크플로와 작은 풀프레임 바디로 영상·일상 스냅에 어울립니다.',
    priceSummary: '약 1,990,000원대 ~',
    platform: '공식몰 · 네이버 · 중고',
    thumbnail: 'https://img.photographyblog.com/reviews/panasonic_lumix_s9/sample_images/panasonic_lumix_s9_01.jpg',
    categories: ['vlog', 'emotional', 'travel'],
  },
  {
    id: 'panasonic-lumix-gh7',
    brand: 'Panasonic',
    model: 'Lumix GH7',
    priceKrw: 2790000,
    popularity: 85,
    description: '마이크로포서즈 영상 플래그십으로 고급 코덱과 손떨림 보정, 긴 촬영 안정성이 강점입니다.',
    priceSummary: '약 2,790,000원대 ~',
    platform: '공식몰 · 다나와 · 네이버',
    thumbnail: '/images/cameras/panasonic-lumix-gh7.png',
    categories: ['vlog', 'trending'],
  },
  {
    id: 'om-system-om-3',
    brand: 'OM System',
    model: 'OM-3',
    priceKrw: 2390000,
    popularity: 81,
    description: '클래식한 디자인에 방진방적과 강력한 손떨림 보정을 더한 여행·아웃도어형 미러리스입니다.',
    priceSummary: '약 2,390,000원대 ~',
    platform: '공식몰 · 네이버 · 중고',
    thumbnail: 'https://4.img-dpreview.com/files/p/TC190x190S190x190~sample_galleries/1564684221/4315193761.jpg',
    categories: ['travel', 'vintage', 'emotional'],
  },
  {
    id: 'fujifilm-x-m5',
    brand: 'Fujifilm',
    model: 'X-M5',
    priceKrw: 1190000,
    popularity: 88,
    description: '작은 바디와 필름 시뮬레이션, 영상 친화 UI를 갖춘 입문·브이로그용 X 시리즈입니다.',
    priceSummary: '약 1,190,000원대 ~',
    platform: '공식몰 · 쿠팡 · 네이버',
    thumbnail: 'https://1.img-dpreview.com/files/p/TC190x190S190x190~sample_galleries/6845601350/1452105376.jpg',
    categories: ['beginner', 'vlog', 'emotional'],
  },
  {
    id: 'leica-d-lux-8',
    brand: 'Leica',
    model: 'D-Lux 8',
    priceKrw: 2390000,
    popularity: 77,
    description: '밝은 줌렌즈와 클래식한 조작계를 갖춘 프리미엄 컴팩트로 일상 스냅에 잘 맞습니다.',
    priceSummary: '약 2,390,000원대 ~',
    platform: '공식몰 · 네이버 · 중고',
    thumbnail: 'https://4.img-dpreview.com/files/p/TS60x60PFFFFFF00~products/leica_dlux8/cd1fcfa8664d44b38cb04577f0b2ada4.png',
    categories: ['vintage', 'emotional', 'travel'],
  },
  {
    id: 'sigma-fp-l',
    brand: 'Sigma',
    model: 'fp L',
    priceKrw: 2990000,
    popularity: 72,
    description: '초소형 풀프레임 바디와 61MP 센서가 특징인 모듈형 카메라로 사진·시네마 작업에 독특합니다.',
    priceSummary: '약 2,990,000원대 ~',
    platform: '공식몰 · 다나와 · 중고',
    thumbnail: 'https://img.photographyblog.com/reviews/sigma_fp_l/sample_images/sigma_fp_l_01.jpg',
    categories: ['emotional', 'vintage'],
  },
  {
    id: 'kodak-pixpro-fz55',
    brand: 'Kodak',
    model: 'Pixpro FZ55',
    priceKrw: 230000,
    popularity: 74,
    description: '가볍고 저렴한 CCD 감성 컴팩트로 휴대폰과 다른 색감의 일상 기록용으로 찾는 모델입니다.',
    priceSummary: '약 230,000원대 ~',
    platform: '쿠팡 · 네이버 · 중고',
    thumbnail: 'https://m.media-amazon.com/images/I/71lI8A2AvzL._AC_SL1500_.jpg',
    categories: ['value', 'vintage', 'travel'],
  },
];
