/**
 * Picory 상품 페이지 — 더미 상품 데이터 (thumbnail, categories 필수)
 * 썸네일 경로: 사이트 루트 기준 images/cameras (정적 배포 시 public 동일)
 */
export const PICORY_PRODUCT_MOCK = [
  {
    id: 'fujifilm-x100vi',
    brand: 'Fujifilm',
    model: 'X100VI',
    /** 정렬용: 대략 최저가(원), 인기순 가중치 */
    priceKrw: 2190000,
    popularity: 98,
    description: '필름 감성과 고급 AF를 담은 일상용 고정렌즈 컴팩트',
    priceSummary: '약 2,190,000원대 · 정가 기준',
    platform: '네이버 쇼핑 · 쿠팡 · 공식몰',
    thumbnail: '/images/cameras/fujifilm-x100vi.png',
    categories: ['trending', 'emotional', 'travel'],
  },
  {
    id: 'canon-eos-r10',
    brand: 'Canon',
    model: 'EOS R10',
    priceKrw: 920000,
    popularity: 82,
    description: '가볍고 빠른 AF로 시작하기 좋은 APS-C 미러리스',
    priceSummary: '약 920,000원대 ~',
    platform: '쿠팡 · 다나와 · 중고나라',
    thumbnail: '/images/cameras/canon-eos-r10.png',
    categories: ['beginner', 'value', 'travel'],
  },
  {
    id: 'sony-zv-e10-ii',
    brand: 'Sony',
    model: 'ZV-E10 II',
    priceKrw: 1280000,
    popularity: 92,
    description: '브이로그 촬영에 맞춘 가벼운 APS-C 바디',
    priceSummary: '약 1,280,000원대 ~',
    platform: '네이버 · 공식 스토어 · 온라인 면세',
    thumbnail: '/images/cameras/sony-zv-e10-ii.png',
    categories: ['vlog', 'beginner', 'trending'],
  },
  {
    id: 'ricoh-gr-iiix',
    brand: 'Ricoh',
    model: 'GR IIIx',
    priceKrw: 1590000,
    popularity: 88,
    description: '40mm 화각의 스트리트·여행용 프리미엄 컴팩트',
    priceSummary: '약 1,590,000원대 ~',
    platform: '공식몰 · 온라인 · 중고',
    thumbnail: '/images/cameras/ricoh-gr-iiix.png',
    categories: ['travel', 'emotional', 'trending'],
  },
  {
    id: 'sony-a7c-ii',
    brand: 'Sony',
    model: 'A7C II',
    priceKrw: 2390000,
    popularity: 96,
    description: '작은 바디에 풀프레임 센서를 담은 올라운더',
    priceSummary: '약 2,390,000원대 ~',
    platform: '다나와 · 쿠팡 · 오프라인 대리점',
    thumbnail: '/images/cameras/sony-a7c-ii.png',
    categories: ['trending', 'emotional', 'vlog'],
  },
  {
    id: 'nikon-z-fc',
    brand: 'Nikon',
    model: 'Z fc',
    priceKrw: 1190000,
    popularity: 80,
    description: '레트로 다이얼과 현대적 성능의 APS-C 바디',
    priceSummary: '약 1,190,000원대 ~',
    platform: '네이버 · 공식몰 · 중고나라',
    thumbnail: '/images/cameras/nikon-z-fc.png',
    categories: ['vintage', 'emotional', 'travel'],
  },
  {
    id: 'canon-g7x-mark-iii',
    brand: 'Canon',
    model: 'PowerShot G7 X Mark III',
    priceKrw: 950000,
    popularity: 90,
    description: '4K 영상과 vlog에 강한 휴대형 1인치 컴팩트',
    priceSummary: '약 950,000원대 ~',
    platform: '쿠팡 · 온라인 면세 · 중고',
    thumbnail: '/images/cameras/canon-g7x-mark-iii.png',
    categories: ['vlog', 'travel', 'value'],
  },
  {
    id: 'dji-osmo-pocket-3',
    brand: 'DJI',
    model: 'Osmo Pocket 3',
    priceKrw: 649000,
    popularity: 91,
    description: '1인치 센서와 짐벌이 일체형인 포켓 캠',
    priceSummary: '약 649,000원대 ~',
    platform: '공식 스토어 · 쿠팡 · 면세',
    thumbnail: '/images/cameras/dji-osmo-pocket-3.png',
    categories: ['vlog', 'travel', 'trending'],
  },
  {
    id: 'sony-a6700',
    brand: 'Sony',
    model: 'A6700',
    priceKrw: 1520000,
    popularity: 94,
    description: '영상·사진 모두 잡는 상위 APS-C 미러리스',
    priceSummary: '약 1,520,000원대 ~',
    platform: '다나와 · 네이버 · 중고',
    thumbnail: '/images/cameras/sony-a6700.png',
    categories: ['trending', 'vlog', 'travel', 'beginner'],
  },
  {
    id: 'canon-eos-r50',
    brand: 'Canon',
    model: 'EOS R50',
    priceKrw: 980000,
    popularity: 93,
    description: '가벼운 바디로 첫 미러리스 입문에 적합',
    priceSummary: '약 980,000원대 ~',
    platform: '쿠팡 · 온라인 · 중고나라',
    thumbnail: '/images/cameras/canon-eos-r50.png',
    categories: ['beginner', 'value', 'trending'],
  },
  {
    id: 'fujifilm-x-s20',
    brand: 'Fujifilm',
    model: 'X-S20',
    priceKrw: 1780000,
    popularity: 87,
    description: '필름 시뮬레이션과 영상까지 되는 X 시리즈',
    priceSummary: '약 1,780,000원대 ~',
    platform: '공식몰 · 다나와 · 중고',
    thumbnail: '/images/cameras/fujifilm-x-s20.png',
    categories: ['emotional', 'vlog', 'beginner'],
  },
  {
    id: 'canon-eos-r50-v',
    brand: 'Canon',
    model: 'EOS R50 V',
    priceKrw: 1180000,
    popularity: 79,
    description: '세로 영상·라이브 촬영에 맞춘 입문형 바디',
    priceSummary: '약 1,180,000원대 ~',
    platform: '네이버 · 쿠팡 · 공식',
    thumbnail: '/images/cameras/canon-eos-r50-v.png',
    categories: ['vlog', 'beginner', 'trending'],
  },
  {
    id: 'nikon-z50ii',
    brand: 'Nikon',
    model: 'Z50II',
    priceKrw: 1290000,
    popularity: 89,
    description: '가족·여행·영상까지 두루 쓰기 좋은 올라운더',
    priceSummary: '약 1,290,000원대 ~',
    platform: '네이버 · 중고나라 · 공식몰',
    thumbnail: '/images/cameras/nikon-z50ii.png',
    categories: ['beginner', 'travel', 'trending'],
  },
  {
    id: 'canon-eos-r8',
    brand: 'Canon',
    model: 'EOS R8',
    priceKrw: 1890000,
    popularity: 86,
    description: '가벼운 무게의 풀프레임 입문·여행용',
    priceSummary: '약 1,890,000원대 ~',
    platform: '쿠팡 · 네이버 · 다나와',
    thumbnail: '/images/cameras/canon-eos-r8.png',
    categories: ['travel', 'emotional', 'value'],
  },
  {
    id: 'sony-rx100-vii',
    brand: 'Sony',
    model: 'RX100 VII',
    priceKrw: 1490000,
    popularity: 84,
    description: '24-200mm 줌을 담은 프리미엄 컴팩트',
    priceSummary: '약 1,490,000원대 ~',
    platform: '네이버 · 쿠팡 · 중고',
    thumbnail: '/images/cameras/sony-rx100-vii.png',
    categories: ['travel', 'value', 'vlog'],
  },
  {
    id: 'panasonic-lumix-s9',
    brand: 'Panasonic',
    model: 'Lumix S9',
    priceKrw: 1990000,
    popularity: 83,
    description: '영상 컬러 워크플로에 특화된 풀프레임 바디',
    priceSummary: '약 1,990,000원대 ~',
    platform: '공식몰 · 네이버 · 중고',
    thumbnail: '/images/cameras/panasonic-lumix-s9.png',
    categories: ['vlog', 'emotional', 'travel'],
  },
  {
    id: 'panasonic-lumix-gh7',
    brand: 'Panasonic',
    model: 'Lumix GH7',
    priceKrw: 2790000,
    popularity: 85,
    description: '프로 영상 촬영용 M4/3 플래그십 바디',
    priceSummary: '약 2,790,000원대 ~',
    platform: '공식몰 · 다나와 · 네이버',
    thumbnail: '/images/cameras/panasonic-lumix-gh7.png',
    categories: ['vlog', 'trending'],
  },
  {
    id: 'om-system-om-3',
    brand: 'OM System',
    model: 'OM-3',
    priceKrw: 2390000,
    popularity: 81,
    description: '방진·여행·아웃도어에 강한 클래식 바디',
    priceSummary: '약 2,390,000원대 ~',
    platform: '공식몰 · 네이버 · 중고',
    thumbnail: '/images/cameras/om-system-om-3.png',
    categories: ['travel', 'vintage', 'emotional'],
  },
  {
    id: 'fujifilm-x-m5',
    brand: 'Fujifilm',
    model: 'X-M5',
    priceKrw: 1190000,
    popularity: 88,
    description: '입문과 브이로그를 겨냥한 가벼운 X 시리즈',
    priceSummary: '약 1,190,000원대 ~',
    platform: '공식몰 · 쿠팡 · 네이버',
    thumbnail: '/images/cameras/fujifilm-x-m5.png',
    categories: ['beginner', 'vlog', 'emotional'],
  },
  {
    id: 'leica-d-lux-8',
    brand: 'Leica',
    model: 'D-Lux 8',
    priceKrw: 2390000,
    popularity: 77,
    description: 'Leica 감성의 프리미엄 일상 스냅 컴팩트',
    priceSummary: '약 2,390,000원대 ~',
    platform: '공식몰 · 네이버 · 중고',
    thumbnail: '/images/cameras/leica-d-lux-8.png',
    categories: ['vintage', 'emotional', 'travel'],
  },
  {
    id: 'sigma-fp-l',
    brand: 'Sigma',
    model: 'fp L',
    priceKrw: 2990000,
    popularity: 72,
    description: '초소형 모듈형 풀프레임 영상·사진 바디',
    priceSummary: '약 2,990,000원대 ~',
    platform: '공식몰 · 다나와 · 중고',
    thumbnail: '/images/cameras/sigma-fp-l.png',
    categories: ['emotional', 'vintage'],
  },
  {
    id: 'kodak-pixpro-fz55',
    brand: 'Kodak',
    model: 'Pixpro FZ55',
    priceKrw: 230000,
    popularity: 74,
    description: '저렴하게 즐기는 CCD 감성 컴팩트',
    priceSummary: '약 230,000원대 ~',
    platform: '쿠팡 · 네이버 · 중고',
    thumbnail: '/images/cameras/kodak-pixpro-fz55.png',
    categories: ['value', 'vintage', 'travel'],
  },
];
